# macOS-specific file paths
file.upload.physical-path-materials=/Volumes/sharefolder/LMSProject/materials/
file.upload.physical-path=/Volumes/sharefolder/LMSProject/

# ?? ??? ?? (macOS)
file.upload.logical-path-assignments=assignments/
file.upload.physical-path-assignments=/Volumes/sharefolder/LMSProject/assignments/