# macOS-specific file paths
file.upload.physical-path-materials=${user.home}/lms_uploads/materials/
file.upload.physical-path=${user.home}/lms_uploads/
file.upload.physical-profile-path=${user.home}/lms_uploads/profile/

# ?? ??? ?? (macOS)
file.upload.logical-path-assignments=assignments/
file.upload.physical-path-assignments=${user.home}/lms_uploads/assignments/
