# [?? ?? ?? ?? ??]
fileUpload.virtualRootPath=/serverfile

# [C???? ??] - ?? ??? ?? ?? ???
fileUpload.rootPath=C:/FileRepository/
fileUpload.prducimage=product
fileUpload.noticePath=notice
fileUpload.userPath=user
fileUpload.temp=temp
fileUpload.homeworkPath=homework
fileUpload.submitPath=submit

# [???? Z???? ?? ??]
# ???? ?? Z???? ?? ??? ???? ???.
win.file.upload.path=file:///Z:/LMSProject/

# [??? ???? ??? ?? ??]
# ??? ?? ??(Command+K) ? ???? ?????.
mac.file.upload.path=file:/Volumes/sharefolder/LMSProject/

# [?? ?? ?? ??]
file.upload.logical-profile=profile/
file.upload.logical-resume=resume/
file.upload.logical-qna=qna01/
file.upload.logical-materials=materials/
fileUpload.logical-path-materials=materials/
#file.upload.physical-path-materials=/Volumes/sharefolder/LMSProject/materials/
#file.upload.physical-path=/Volumes/sharefolder/LMSProject/

# ?? ??? ?? ??
file.upload.logical-path-assignments=/jquery_img/
fileUpload.logical-path-assignments=/jquery_img/
file.upload.physical-path-assignments=${user.home}/lms_uploads/assignments/
file.upload.physical-path=${user.home}/lms_uploads/
file.upload.physical-profile-path=//192.168.0.130/sharefolder/LMSProject/profile/
file.upload.physical-path-materials=\\\\192.168.0.130\\sharefolder\\LMSProject\\materials