# Windows-specific file paths
file.upload.physical-path-materials=\\\\192.168.0.130\\sharefolder\\LMSProject\\materials
file.upload.physical-path=${user.home}/lms_uploads/
file.upload.physical-profile-path=//192.168.0.130/sharefolder/LMSProject/profile/

# ?? ??? ?? (Windows)
file.upload.logical-path-assignments=assignments/
file.upload.physical-path-assignments=${user.home}/lms_uploads/assignments/
